name: IPTV Auto Proxy Playlist

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Source Playlist
        run: |
          curl -L "https://elitebeam.shop/iptv/ONdQ2h/Playlist.m3u" -o full.m3u

      - name: Filter Useful Channels
        run: |
          echo "#EXTM3U" > playlist.m3u
          grep -i -A1 -E "india|hindi|star sports|sony sports|sports18|dd sports|ipl|cricket|news" full.m3u >> playlist.m3u || true

      - name: Clean Duplicate Links
        run: |
          awk '!seen[$0]++' playlist.m3u > clean.m3u
          mv clean.m3u playlist.m3u

      - name: Commit & Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto update $(date)" || echo "No changes"
          git push
